#pragma once

#include "ggml.h" // ggml_op

#include <string>
#include <set>
#include <vector>

//
// gguf constants (sync with gguf.py)
//

enum llm_arch {
    LLM_ARCH_CLIP = 0,
    LLM_ARCH_LLAMA = 1,
    LLM_ARCH_LLAMA4 = 2,
    LLM_ARCH_DECI = 3,
    LLM_ARCH_FALCON = 4,
    LLM_ARCH_BAICHUAN = 5,
    LLM_ARCH_GROK = 6,
    LLM_ARCH_GPT2 = 7,
    LLM_ARCH_GPTJ = 8,
    LLM_ARCH_GPTNEOX = 9,
    LLM_ARCH_MPT = 10,
    LLM_ARCH_STARCODER = 11,
    LLM_ARCH_REFACT = 12,
    LLM_ARCH_BERT = 13,
    LLM_ARCH_MODERN_BERT = 14,
    LLM_ARCH_NOMIC_BERT = 15,
    LLM_ARCH_NOMIC_BERT_MOE = 16,
    LLM_ARCH_NEO_BERT = 17,
    LLM_ARCH_JINA_BERT_V2 = 18,
    LLM_ARCH_JINA_BERT_V3 = 19,
    LLM_ARCH_EUROBERT = 20,
    LLM_ARCH_BLOOM = 21,
    LLM_ARCH_STABLELM = 22,
    LLM_ARCH_QWEN = 23,
    LLM_ARCH_QWEN2 = 24,
    LLM_ARCH_QWEN2MOE = 25,
    LLM_ARCH_QWEN2VL = 26,
    LLM_ARCH_QWEN3 = 27,
    LLM_ARCH_QWEN3MOE = 28,
    LLM_ARCH_QWEN3NEXT = 29,
    LLM_ARCH_QWEN3VL = 30,
    LLM_ARCH_QWEN3VLMOE = 31,
    LLM_ARCH_QWEN35 = 32,
    LLM_ARCH_QWEN35MOE = 33,
    LLM_ARCH_QWEN4EXP = 143,
    LLM_ARCH_PHI2 = 34,

    LLM_ARCH_CLEF = 156,
    LLM_ARCH_PHI3 = 35,
    LLM_ARCH_PHIMOE = 36,
    LLM_ARCH_PLAMO = 37,
    LLM_ARCH_PLAMO2 = 38,
    LLM_ARCH_PLAMO3 = 39,
    LLM_ARCH_CODESHELL = 40,
    LLM_ARCH_ORION = 41,
    LLM_ARCH_INTERNLM2 = 42,
    LLM_ARCH_MINICPM = 43,
    LLM_ARCH_MINICPM3 = 44,
    LLM_ARCH_GEMMA = 45,
    LLM_ARCH_GEMMA2 = 46,
    LLM_ARCH_GEMMA3 = 47,
    LLM_ARCH_GEMMA3N = 48,
    LLM_ARCH_GEMMA4 = 49,
    LLM_ARCH_GEMMA4_ASSISTANT = 50,
    LLM_ARCH_GEMMA_EMBEDDING = 51,
    LLM_ARCH_STARCODER2 = 52,
    LLM_ARCH_MAMBA = 53,
    LLM_ARCH_MAMBA2 = 54,
    LLM_ARCH_JAMBA = 55,
    LLM_ARCH_FALCON_H1 = 56,
    LLM_ARCH_XVERSE = 57,
    LLM_ARCH_COMMAND_R = 58,
    LLM_ARCH_COHERE2 = 59,
    LLM_ARCH_COHERE2MOE = 60,
    LLM_ARCH_DBRX = 61,
    LLM_ARCH_OLMO = 62,
    LLM_ARCH_OLMO2 = 63,
    LLM_ARCH_OLMOE = 64,
    LLM_ARCH_MUSE_GLIMMER = 65,
    LLM_ARCH_OPENELM = 66,
    LLM_ARCH_ARCTIC = 67,
    LLM_ARCH_DEEPSEEK = 68,
    LLM_ARCH_DEEPSEEK2 = 69,
    LLM_ARCH_DEEPSEEK2OCR = 70,
    LLM_ARCH_DEEPSEEK32 = 71,
    LLM_ARCH_DEEPSEEK4 = 72,
    LLM_ARCH_CHATGLM = 73,
    LLM_ARCH_GLM4 = 74,
    LLM_ARCH_GLM4_MOE = 75,
    LLM_ARCH_GLM_DSA = 76,
    LLM_ARCH_BITNET = 77,
    LLM_ARCH_T5 = 78,
    LLM_ARCH_T5ENCODER = 79,
    LLM_ARCH_JAIS = 80,
    LLM_ARCH_JAIS2 = 81,
    LLM_ARCH_NEMOTRON = 82,
    LLM_ARCH_NEMOTRON_H = 83,
    LLM_ARCH_NEMOTRON_H_MOE = 84,
    LLM_ARCH_EXAONE = 85,
    LLM_ARCH_EXAONE4 = 86,
    LLM_ARCH_EXAONE_MOE = 87,
    LLM_ARCH_RWKV6 = 88,
    LLM_ARCH_RWKV6QWEN2 = 89,
    LLM_ARCH_RWKV7 = 90,
    LLM_ARCH_ARWKV7 = 91,
    LLM_ARCH_GRANITE = 92,
    LLM_ARCH_GRANITE_MOE = 93,
    LLM_ARCH_GRANITE_HYBRID = 94,
    LLM_ARCH_GRANITE_SWITCH = 144,
    LLM_ARCH_GRANITE_SWA = 145,
    LLM_ARCH_CHAMELEON = 95,
    LLM_ARCH_WAVTOKENIZER_DEC = 96,
    LLM_ARCH_PLM = 97,
    LLM_ARCH_BAILINGMOE = 98,
    LLM_ARCH_BAILINGMOE2 = 99,
    LLM_ARCH_BAILINGMOE3 = 146,
    LLM_ARCH_DOTS1 = 100,
    LLM_ARCH_DOTS3NOTE = 147,
    LLM_ARCH_ARCEE = 101,
    LLM_ARCH_AFMOE = 102,
    LLM_ARCH_LAGUNA = 103,
    LLM_ARCH_ERNIE4_5 = 104,
    LLM_ARCH_ERNIE4_5_MOE = 105,
    LLM_ARCH_HUNYUAN_MOE = 106,
    LLM_ARCH_HUNYUAN_DENSE = 107,
    LLM_ARCH_HUNYUAN_VL = 108,
    LLM_ARCH_HY_V3 = 109,
    LLM_ARCH_SMOLLM3 = 110,
    LLM_ARCH_OPENAI_MOE = 111,
    LLM_ARCH_LFM2 = 112,
    LLM_ARCH_LFM2MOE = 113,
    LLM_ARCH_DREAM = 114,
    LLM_ARCH_SMALLTHINKER = 115,
    LLM_ARCH_LLADA = 116,
    LLM_ARCH_LLADA_MOE = 117,
    LLM_ARCH_SEED_OSS = 118,
    LLM_ARCH_GROVEMOE = 119,
    LLM_ARCH_APERTUS = 120,
    LLM_ARCH_MINIMAX_M2 = 121,
    LLM_ARCH_COGVLM = 122,
    LLM_ARCH_RND1 = 123,
    LLM_ARCH_PANGU_EMBED = 124,
    LLM_ARCH_MISTRAL3 = 125,
    LLM_ARCH_MISTRAL4 = 126,
    LLM_ARCH_PADDLEOCR = 127,
    LLM_ARCH_MIMO2 = 128,
    LLM_ARCH_STEP35 = 129,
    LLM_ARCH_LLAMA_EMBED = 130,
    LLM_ARCH_MAINCODER = 131,
    LLM_ARCH_KIMI_LINEAR = 132,
    LLM_ARCH_DFLASH_DRAFT = 133,
    LLM_ARCH_GEMMA4_DFLASH_DRAFT = 134,
    LLM_ARCH_KIMI_K3 = 148,
    LLM_ARCH_TALKIE = 135,

    LLM_ARCH_GLM5_NEXT = 155,
    LLM_ARCH_MELLUM = 136,
    LLM_ARCH_EAGLE3 = 137,
    LLM_ARCH_MINIMAX_M3 = 138,
    LLM_ARCH_DFLASH = 139,
    LLM_ARCH_NANBEIGE = 140,
    LLM_ARCH_QWEN3TTS = 141,
    LLM_ARCH_POCKETTTS = 149,
    LLM_ARCH_MINIMAX_01 = 150,
    LLM_ARCH_MAPLE = 151,
    LLM_ARCH_HY_V4 = 152,
    LLM_ARCH_SPARK2_5 = 153,
    LLM_ARCH_HRM_TEXT = 154,
    LLM_ARCH_UNKNOWN = 142,
};

enum llm_kv {
    LLM_KV_GENERAL_TYPE = 0,
    LLM_KV_GENERAL_ARCHITECTURE = 1,
    LLM_KV_GENERAL_QUANTIZATION_VERSION = 2,
    LLM_KV_GENERAL_ALIGNMENT = 3,
    LLM_KV_GENERAL_FILE_TYPE = 4,
    LLM_KV_GENERAL_SAMPLING_SEQUENCE = 5,
    LLM_KV_GENERAL_SAMPLING_TOP_K = 6,
    LLM_KV_GENERAL_SAMPLING_TOP_P = 7,
    LLM_KV_GENERAL_SAMPLING_MIN_P = 8,
    LLM_KV_GENERAL_SAMPLING_XTC_PROBABILITY = 9,
    LLM_KV_GENERAL_SAMPLING_XTC_THRESHOLD = 10,
    LLM_KV_GENERAL_SAMPLING_TEMP = 11,
    LLM_KV_GENERAL_SAMPLING_PENALTY_LAST_N = 12,
    LLM_KV_GENERAL_SAMPLING_PENALTY_REPEAT = 13,
    LLM_KV_GENERAL_SAMPLING_MIROSTAT = 14,
    LLM_KV_GENERAL_SAMPLING_MIROSTAT_TAU = 15,
    LLM_KV_GENERAL_SAMPLING_MIROSTAT_ETA = 16,
    LLM_KV_GENERAL_NAME = 17,
    LLM_KV_GENERAL_AUTHOR = 18,
    LLM_KV_GENERAL_VERSION = 19,
    LLM_KV_GENERAL_URL = 20,
    LLM_KV_GENERAL_DESCRIPTION = 21,
    LLM_KV_GENERAL_LICENSE = 22,
    LLM_KV_GENERAL_SOURCE_URL = 23,
    LLM_KV_GENERAL_SOURCE_HF_REPO = 24,

    LLM_KV_VOCAB_SIZE = 25,
    LLM_KV_CONTEXT_LENGTH = 26,
    LLM_KV_EMBEDDING_LENGTH = 27,
    LLM_KV_EMBEDDING_LENGTH_OUT = 28,
    LLM_KV_EMBEDDING_LENGTH_PER_LAYER = 29,
    LLM_KV_FEATURES_LENGTH = 30,
    LLM_KV_BLOCK_COUNT = 31,
    LLM_KV_LEADING_DENSE_BLOCK_COUNT = 32,
    LLM_KV_ATTN_RES_BLOCK_SIZE = 217,
    LLM_KV_ACTIVATION_SITU_BETA = 218,
    LLM_KV_ACTIVATION_SITU_LINEAR_BETA = 219,
    LLM_KV_FEED_FORWARD_LENGTH = 33,
    LLM_KV_EXPERT_FEED_FORWARD_LENGTH = 34,
    LLM_KV_EXPERT_SHARED_FEED_FORWARD_LENGTH = 35,
    LLM_KV_EXPERT_CHUNK_FEED_FORWARD_LENGTH = 36,
    LLM_KV_SWIGLU_CLAMP_EXP = 37,
    LLM_KV_SWIGLU_CLAMP_SHEXP = 38,
    LLM_KV_USE_PARALLEL_RESIDUAL = 39,
    LLM_KV_TENSOR_DATA_LAYOUT = 40,
    LLM_KV_EXPERT_COUNT = 41,
    LLM_KV_EXPERT_USED_COUNT = 42,
    LLM_KV_EXPERT_SHARED_COUNT = 43,
    LLM_KV_EXPERT_GROUP_COUNT = 44,
    LLM_KV_EXPERT_GROUP_USED_COUNT = 45,
    LLM_KV_EXPERT_WEIGHTS_SCALE = 46,
    LLM_KV_EXPERT_WEIGHTS_NORM = 47,
    LLM_KV_EXPERT_LATENT_LENGTH = 220,
    LLM_KV_EXPERT_GATING_FUNC = 48,
    LLM_KV_EXPERT_GROUP_SCALE = 49,
    LLM_KV_EXPERTS_PER_GROUP = 50,
    LLM_KV_MOE_EVERY_N_LAYERS = 51,
    LLM_KV_MOE_LATENT_SIZE = 52,
    LLM_KV_NEXTN_PREDICT_LAYERS = 53,
    // Fork extension. Keep it out of the legacy sequential range below:
    // inserting it there aliases LLM_KV_EMBEDDING_SCALE with the explicitly
    // numbered LLM_KV_TOKEN_SHIFT_COUNT.
    LLM_KV_NEXTN_SHARED_TARGET_TENSORS = 247,
    LLM_KV_NUM_DEEPSTACK_LAYERS = 54,
    LLM_KV_DEEPSTACK_MAPPING = 55,
    LLM_KV_HIDDEN_ACT = 56,
    LLM_KV_POOLING_TYPE = 57,
    LLM_KV_LOGIT_SCALE = 58,
    LLM_KV_DECODER_START_TOKEN_ID = 59,
    LLM_KV_DECODER_BLOCK_COUNT = 60,
    LLM_KV_ATTN_LOGIT_SOFTCAPPING = 61,
    LLM_KV_ROUTER_LOGIT_SOFTCAPPING = 62,
    LLM_KV_FINAL_LOGIT_SOFTCAPPING = 63,
    LLM_KV_SWIN_NORM = 64,
    LLM_KV_RESCALE_EVERY_N_LAYERS = 65,
    LLM_KV_TIME_MIX_EXTRA_DIM = 66,
    LLM_KV_TIME_DECAY_EXTRA_DIM = 67,
    LLM_KV_RESIDUAL_SCALE = 68,
    LLM_KV_EMBEDDING_SCALE = 69,
    LLM_KV_ADAPTER_COUNT = 221,
    LLM_KV_ADAPTER_TOKEN_IDS_ACTIVATE = 222,
    LLM_KV_ADAPTER_TOKEN_IDS_SUBSTITUTE = 223,
    LLM_KV_ADAPTER_LORA_RANK = 224,
    LLM_KV_ADAPTER_ROUTER_GAIN = 225,
    LLM_KV_TOKEN_SHIFT_COUNT = 70,
    LLM_KV_INTERLEAVE_MOE_LAYER_STEP = 71,
    LLM_KV_FULL_ATTENTION_INTERVAL = 72,
    LLM_KV_NUM_LOOPS = 73,
    LLM_KV_SKIP_LOOP_FINAL_NORM = 74,

    LLM_KV_ATTENTION_HEAD_COUNT = 75,
    LLM_KV_ATTENTION_HEAD_COUNT_KV = 76,
    LLM_KV_ATTENTION_MAX_ALIBI_BIAS = 77,
    LLM_KV_ATTENTION_CLAMP_KQV = 78,
    LLM_KV_ATTENTION_KEY_LENGTH = 79,
    LLM_KV_ATTENTION_VALUE_LENGTH = 80,
    LLM_KV_ATTENTION_LAYERNORM_EPS = 81,
    LLM_KV_ATTENTION_LAYERNORM_RMS_EPS = 82,
    LLM_KV_ATTENTION_GROUPNORM_EPS = 83,
    LLM_KV_ATTENTION_GROUPNORM_GROUPS = 84,
    LLM_KV_ATTENTION_CAUSAL = 85,
    LLM_KV_ATTENTION_Q_LORA_RANK = 86,
    LLM_KV_ATTENTION_KV_LORA_RANK = 87,
    LLM_KV_ATTENTION_DECAY_LORA_RANK = 88,
    LLM_KV_ATTENTION_ICLR_LORA_RANK = 89,
    LLM_KV_ATTENTION_VALUE_RESIDUAL_MIX_LORA_RANK = 90,
    LLM_KV_ATTENTION_GATE_LORA_RANK = 91,
    LLM_KV_ATTENTION_RELATIVE_BUCKETS_COUNT = 92,
    LLM_KV_ATTENTION_SLIDING_WINDOW = 93,
    LLM_KV_ATTENTION_SLIDING_WINDOW_PATTERN = 94,
    LLM_KV_ATTENTION_SCALE = 95,
    LLM_KV_ATTENTION_ROPE_PATTERN = 226,

    LLM_KV_ATTENTION_OUTPUT_SCALE = 96,
    LLM_KV_ATTENTION_VALUE_SCALE = 97,
    LLM_KV_ATTENTION_TEMPERATURE_LENGTH = 98,
    LLM_KV_ATTENTION_TEMPERATURE_SCALE = 99,
    LLM_KV_ATTENTION_KEY_LENGTH_MLA = 100,
    LLM_KV_ATTENTION_VALUE_LENGTH_MLA = 101,
    LLM_KV_ATTENTION_KEY_LENGTH_SWA = 102,
    LLM_KV_ATTENTION_VALUE_LENGTH_SWA = 103,
    LLM_KV_ATTENTION_KEY_LENGTH_MLA_SWA = 227,
    LLM_KV_ATTENTION_VALUE_LENGTH_MLA_SWA = 228,
    LLM_KV_ATTENTION_KV_LORA_RANK_SWA = 229,
    LLM_KV_ATTENTION_INDEXER_HEAD_COUNT = 104,
    LLM_KV_ATTENTION_INDEXER_KEY_LENGTH = 105,
    LLM_KV_ATTENTION_INDEXER_TOP_K = 106,
    LLM_KV_ATTENTION_INDEXER_BLOCK_SIZE = 107,
    LLM_KV_ATTENTION_INDEXER_LOCAL_BLOCKS = 108,
    LLM_KV_ATTENTION_INDEXER_TYPES = 109,
    LLM_KV_ATTENTION_INDEXER_KPOOL = 255,
    LLM_KV_ATTENTION_INDEXER_KPOOL_SELECT_TAIL = 256,
    LLM_KV_ATTENTION_OUTPUT_GROUP_COUNT = 110,
    LLM_KV_ATTENTION_OUTPUT_LORA_RANK = 111,
    LLM_KV_ATTENTION_COMPRESS_ROPE_FREQ_BASE = 112,
    LLM_KV_ATTENTION_COMPRESS_RATIOS = 113,
    LLM_KV_ATTENTION_SHARED_KV_LAYERS = 114,
    LLM_KV_ATTENTION_RECURRENT_LAYERS = 115,

    LLM_KV_HYPER_CONNECTION_COUNT = 116,
    LLM_KV_HYPER_CONNECTION_SINKHORN_ITERATIONS = 117,
    LLM_KV_HYPER_CONNECTION_EPSILON = 118,
    LLM_KV_HYPER_CONNECTION_LOW_RANK = 230,

    LLM_KV_PLE_LAYERS = 231,
    LLM_KV_PLE_NGRAM_SIZE = 232,
    LLM_KV_PLE_HEADS_PER_NGRAM = 233,
    LLM_KV_PLE_CONV_KERNEL = 234,
    LLM_KV_PLE_LAYER_MULTIPLIERS = 235,
    LLM_KV_PLE_HEAD_OFFSETS = 236,
    LLM_KV_PLE_HEAD_VOCAB_SIZES = 237,
    LLM_KV_PLE_EOS_TOKEN_ID = 238,
    LLM_KV_PLE_IMAGE_TOKEN_ID = 239,

    LLM_KV_HASH_LAYER_COUNT = 119,

    LLM_KV_ROPE_DIMENSION_COUNT = 120,
    LLM_KV_ROPE_DIMENSION_COUNT_SWA = 121,
    LLM_KV_ROPE_DIMENSION_SECTIONS = 122,
    LLM_KV_ROPE_FREQ_BASE = 123,
    LLM_KV_ROPE_FREQ_BASE_SWA = 124,
    LLM_KV_ROPE_SCALE_LINEAR = 125,
    LLM_KV_ROPE_SCALING_TYPE = 126,
    LLM_KV_ROPE_SCALING_FACTOR = 127,
    LLM_KV_ROPE_SCALING_ALPHA = 128,
    LLM_KV_ROPE_SCALING_ATTN_FACTOR = 129,
    LLM_KV_ROPE_SCALING_ORIG_CTX_LEN = 130,
    LLM_KV_ROPE_SCALING_FINETUNED = 131,
    LLM_KV_ROPE_SCALING_YARN_LOG_MUL = 132,
    LLM_KV_ROPE_SCALING_YARN_EXT_FACTOR = 133,
    LLM_KV_ROPE_SCALING_YARN_ATTN_FACTOR = 134,
    LLM_KV_ROPE_SCALING_YARN_BETA_FAST = 135,
    LLM_KV_ROPE_SCALING_YARN_BETA_SLOW = 136,

    LLM_KV_SPLIT_NO = 137,
    LLM_KV_SPLIT_COUNT = 138,
    LLM_KV_SPLIT_TENSORS_COUNT = 139,

    LLM_KV_SSM_INNER_SIZE = 140,
    LLM_KV_SSM_CONV_KERNEL = 141,
    LLM_KV_SSM_STATE_SIZE = 142,
    LLM_KV_SSM_TIME_STEP_RANK = 143,
    LLM_KV_SSM_GROUP_COUNT = 144,
    LLM_KV_SSM_DT_B_C_RMS = 145,

    LLM_KV_KDA_HEAD_DIM = 146,
    LLM_KV_KDA_SAFE_GATE = 240,
    LLM_KV_KDA_GATE_LOWER_BOUND = 241,

    LLM_KV_WKV_HEAD_SIZE = 147,

    LLM_KV_DFLASH_BLOCK_SIZE = 148,
    LLM_KV_DFLASH_MASK_TOKEN_ID = 149,
    LLM_KV_DFLASH_TARGET_LAYER_IDS = 150,
    LLM_KV_DFLASH_N_TARGET_FEATURES = 151,
    LLM_KV_DFLASH2_CONV_KERNEL_SIZE = 152,
    LLM_KV_DFLASH2_CONV_GROUP_SIZE = 153,
    LLM_KV_DFLASH2_SELECTOR_RANK = 154,
    LLM_KV_DFLASH2_SELECTOR_TOP_K = 155,

    LLM_KV_TOKENIZER_MODEL = 156,
    LLM_KV_TOKENIZER_PRE = 157,
    LLM_KV_TOKENIZER_LIST = 158,
    LLM_KV_TOKENIZER_TOKEN_TYPE = 159,
    LLM_KV_TOKENIZER_TOKEN_TYPE_COUNT = 160,
    LLM_KV_TOKENIZER_SCORES = 161,
    LLM_KV_TOKENIZER_MERGES = 162,
    LLM_KV_TOKENIZER_BOS_ID = 163,
    LLM_KV_TOKENIZER_EOS_ID = 164,
    LLM_KV_TOKENIZER_EOT_ID = 165,
    LLM_KV_TOKENIZER_EOM_ID = 166,
    LLM_KV_TOKENIZER_UNK_ID = 167,
    LLM_KV_TOKENIZER_SEP_ID = 168,
    LLM_KV_TOKENIZER_PAD_ID = 169,
    LLM_KV_TOKENIZER_CLS_ID = 170,
    LLM_KV_TOKENIZER_MASK_ID = 171,
    LLM_KV_TOKENIZER_ADD_BOS = 172,
    LLM_KV_TOKENIZER_ADD_EOS = 173,
    LLM_KV_TOKENIZER_ADD_SEP = 174,
    LLM_KV_TOKENIZER_ADD_PREFIX = 175,
    LLM_KV_TOKENIZER_REMOVE_EXTRA_WS = 176,
    LLM_KV_TOKENIZER_PRECOMPILED_CHARSMAP = 177,
    LLM_KV_TOKENIZER_HF_JSON = 178,
    LLM_KV_TOKENIZER_RWKV = 179,
    LLM_KV_TOKENIZER_CHAT_TEMPLATE = 180,
    LLM_KV_TOKENIZER_NORMALIZER_LOWERCASE = 181,
    LLM_KV_TOKENIZER_NORMALIZER_STRIP_ACCENTS = 182,
    LLM_KV_TOKENIZER_FIM_PRE_ID = 183,
    LLM_KV_TOKENIZER_FIM_SUF_ID = 184,
    LLM_KV_TOKENIZER_FIM_MID_ID = 185,
    LLM_KV_TOKENIZER_FIM_PAD_ID = 186,
    LLM_KV_TOKENIZER_FIM_REP_ID = 187,
    LLM_KV_TOKENIZER_FIM_SEP_ID = 188,
    LLM_KV_TOKENIZER_SUPPRESS_TOKENS = 189,

    LLM_KV_ADAPTER_TYPE = 190,
    LLM_KV_ADAPTER_LORA_ALPHA = 191,
    LLM_KV_ADAPTER_LORA_TASK_NAME = 192,
    LLM_KV_ADAPTER_LORA_PROMPT_PREFIX = 193,
    LLM_KV_ADAPTER_ALORA_INVOCATION_TOKENS = 194,

    LLM_KV_POSNET_EMBEDDING_LENGTH = 195,
    LLM_KV_POSNET_BLOCK_COUNT = 196,

    LLM_KV_CONVNEXT_EMBEDDING_LENGTH = 197,
    LLM_KV_CONVNEXT_BLOCK_COUNT = 198,

    LLM_KV_CLASSIFIER_OUTPUT_LABELS = 199,
    LLM_KV_CLASSIFIER_POOLING_TYPE = 257,

    LLM_KV_DECISION_BLOCK_COUNT = 258,
    LLM_KV_DECISION_ROUTING_BLOCK_COUNT = 259,
    LLM_KV_DECISION_HEAD_COUNT = 260,

    LLM_KV_TARGET_LAYERS = 200,
    LLM_KV_TARGET_HIDDEN_SIZE = 201,
    LLM_KV_BLOCK_SIZE = 202,
    LLM_KV_DFLASH_COMPAT_BLOCK_SIZE = 242,
    LLM_KV_DFLASH_CONV_KERNEL_SIZE = 243,
    LLM_KV_DFLASH_CONV_GROUP_SIZE = 244,
    LLM_KV_DFLASH_SELECTOR_RANK = 245,
    LLM_KV_DFLASH_SELECTOR_TOP_K = 246,
    LLM_KV_NORM_BEFORE_RESIDUAL = 203,
    LLM_KV_NORM_BEFORE_FC = 204,

    LLM_KV_SHORTCONV_L_CACHE = 205,

    LLM_KV_XIELU_ALPHA_N = 206,
    LLM_KV_XIELU_ALPHA_P = 207,
    LLM_KV_XIELU_BETA = 208,
    LLM_KV_XIELU_EPS = 209,

    // deprecated:
    LLM_KV_TOKENIZER_PREFIX_ID = 210,
    LLM_KV_TOKENIZER_SUFFIX_ID = 211,
    LLM_KV_TOKENIZER_MIDDLE_ID = 212,

    // sentence-transformers dense layers in and out features
    LLM_KV_DENSE_2_FEAT_IN = 213,
    LLM_KV_DENSE_2_FEAT_OUT = 214,
    LLM_KV_DENSE_3_FEAT_IN = 215,
    LLM_KV_DENSE_3_FEAT_OUT = 216,
    LLM_KV_HYPER_CONNECTION_MAGNITUDE = 248,
    LLM_KV_GENERAL_TENSOR_EXTRA_NAME = 249,
    LLM_KV_GENERAL_TENSOR_EXTRA_PREC_A4 = 250,
    LLM_KV_HRM_LAYERS_PER_STACK = 251,
    LLM_KV_HRM_H_CYCLES = 252,
    LLM_KV_HRM_L_CYCLES = 253,
    LLM_KV_HRM_PREFIX_LM = 254,
};

enum llm_tensor {
    LLM_TENSOR_TOKEN_EMBD = 0,
    LLM_TENSOR_TOKEN_EMBD_NORM = 1,
    LLM_TENSOR_TOKEN_TYPES = 2,
    LLM_TENSOR_POS_EMBD = 3,
    LLM_TENSOR_DENSE_2_OUT = 4,
    LLM_TENSOR_DENSE_3_OUT = 5,
    LLM_TENSOR_OUTPUT = 6,
    LLM_TENSOR_OUTPUT_NORM = 7,
    LLM_TENSOR_OUTPUT_NORM_LFM2 = 8, // fix for wrong tensor name
    LLM_TENSOR_ROPE_FREQS = 9,
    LLM_TENSOR_ROPE_FACTORS_LONG = 10,
    LLM_TENSOR_ROPE_FACTORS_SHORT = 11,
    LLM_TENSOR_ATTN_Q = 12,
    LLM_TENSOR_ATTN_K = 13,
    LLM_TENSOR_ATTN_V = 14,
    LLM_TENSOR_ATTN_QKV = 15,
    LLM_TENSOR_ATTN_OUT = 16,
    LLM_TENSOR_ATTN_NORM = 17,
    LLM_TENSOR_ATTN_NORM_2 = 18,
    LLM_TENSOR_ATTN_OUT_NORM = 19,
    LLM_TENSOR_ATTN_POST_NORM = 20,
    LLM_TENSOR_ATTN_ROT_EMBD = 21,
    LLM_TENSOR_ATTN_SINKS = 22,
    LLM_TENSOR_ATTN_GATE = 23,
    LLM_TENSOR_FFN_GATE_INP = 24,
    LLM_TENSOR_FFN_GATE_INP_SHEXP = 25,
    LLM_TENSOR_FFN_NORM = 26,
    LLM_TENSOR_FFN_POST_NORM = 27,
    LLM_TENSOR_FFN_POST_NORM_1 = 28,
    LLM_TENSOR_FFN_POST_NORM_2 = 29,
    LLM_TENSOR_FFN_PRE_NORM_2 = 30,
    LLM_TENSOR_FFN_GATE = 31,
    LLM_TENSOR_FFN_DOWN = 32,
    LLM_TENSOR_FFN_UP = 33,
    LLM_TENSOR_FFN_ACT = 34,
    LLM_TENSOR_FFN_DOWN_EXP = 35,  // split experts for backward compatibility
    LLM_TENSOR_FFN_GATE_EXP = 36,
    LLM_TENSOR_FFN_UP_EXP = 37,
    LLM_TENSOR_FFN_NORM_EXPS = 38,
    LLM_TENSOR_FFN_DOWN_EXPS = 39, // merged experts
    LLM_TENSOR_FFN_GATE_EXPS = 40,
    LLM_TENSOR_FFN_UP_EXPS = 41,
    LLM_TENSOR_FFN_GATE_UP_EXPS = 42,
    LLM_TENSOR_FFN_DOWN_SHEXP = 43,
    LLM_TENSOR_FFN_GATE_SHEXP = 44,
    LLM_TENSOR_FFN_UP_SHEXP = 45,
    LLM_TENSOR_FFN_DOWN_CHEXPS = 46,
    LLM_TENSOR_FFN_GATE_CHEXPS = 47,
    LLM_TENSOR_FFN_UP_CHEXPS = 48,
    LLM_TENSOR_FFN_EXP_PROBS_B = 49,
    LLM_TENSOR_FFN_LATENT_DOWN = 50,
    LLM_TENSOR_FFN_LATENT_UP = 51,
    LLM_TENSOR_ATTN_Q_NORM = 52,
    LLM_TENSOR_ATTN_K_NORM = 53,
    LLM_TENSOR_LAYER_OUT_NORM = 54,
    LLM_TENSOR_LAYER_OUT_SCALE = 55,
    LLM_TENSOR_POST_ATTN_NORM = 56,
    LLM_TENSOR_POST_MLP_NORM = 57,
    LLM_TENSOR_PER_LAYER_TOKEN_EMBD = 58, // gemma3n
    LLM_TENSOR_PER_LAYER_MODEL_PROJ = 59, // gemma3n
    LLM_TENSOR_PER_LAYER_INP_GATE = 60,   // gemma3n
    LLM_TENSOR_PER_LAYER_PROJ = 61,       // gemma3n
    LLM_TENSOR_PER_LAYER_PROJ_NORM = 62,  // gemma3n
    LLM_TENSOR_PER_LAYER_POST_NORM = 63,  // gemma3n
    LLM_TENSOR_ALTUP_PROJ = 64,           // gemma3n
    LLM_TENSOR_ALTUP_UNEMBD_PROJ = 65,    // gemma3n
    LLM_TENSOR_ALTUP_CORRECT_COEF = 66,   // gemma3n
    LLM_TENSOR_ALTUP_CORRECT_SCALE = 67,  // gemma3n
    LLM_TENSOR_ALTUP_PREDICT_COEF = 68,   // gemma3n
    LLM_TENSOR_ALTUP_ROUTER = 69,         // gemma3n
    LLM_TENSOR_ALTUP_ROUTER_NORM = 70,    // gemma3n
    LLM_TENSOR_LAUREL_L = 71,             // gemma3n
    LLM_TENSOR_LAUREL_R = 72,             // gemma3n
    LLM_TENSOR_LAUREL_POST_NORM = 73,     // gemma3n
    LLM_TENSOR_SSM_IN = 74,
    LLM_TENSOR_SSM_CONV1D = 75,
    LLM_TENSOR_SSM_X = 76,
    LLM_TENSOR_SSM_DT = 77,
    LLM_TENSOR_SSM_DT_NORM = 78,
    LLM_TENSOR_SSM_A = 79,
    LLM_TENSOR_SSM_A_NOSCAN = 80,        // qwen3next special case with MUL instead of SSM_SCAN
    LLM_TENSOR_SSM_B_NORM = 81,
    LLM_TENSOR_SSM_C_NORM = 82,
    LLM_TENSOR_SSM_D = 83,
    LLM_TENSOR_SSM_NORM = 84,
    LLM_TENSOR_SSM_OUT = 85,
    LLM_TENSOR_SSM_BETA_ALPHA = 86,      // qwen3next
    LLM_TENSOR_SSM_ALPHA = 87,           // qwen3.5
    // Kimi Linear KDA (using SSM_ prefix for consistency)
    LLM_TENSOR_SSM_CONV1D_Q = 88,        // kimi: Q conv1d weight
    LLM_TENSOR_SSM_CONV1D_K = 89,        // kimi: K conv1d weight
    LLM_TENSOR_SSM_CONV1D_V = 90,        // kimi: V conv1d weight
    LLM_TENSOR_SSM_F_A = 91,             // kimi: forget gate projection A
    LLM_TENSOR_SSM_F_B = 92,             // kimi: forget gate projection B
    LLM_TENSOR_SSM_BETA = 93,            // kimi: beta mixing coefficient and qwen3.5
    LLM_TENSOR_SSM_G_A = 94,             // kimi: output gate projection A
    LLM_TENSOR_SSM_G_B = 95,             // kimi: output gate projection B
    // Move colliding incoming IDs beyond the fork's existing schema IDs.
    // 252..256 are already used by the fork selector and conv tensors.
    LLM_TENSOR_SSM_G = 284,               // kimi-k3: full-rank KDA gate
    LLM_TENSOR_ATTN_RES_SCORE = 285,      // kimi-k3: fused res_norm*res_proj (pre-attn)
    LLM_TENSOR_FFN_RES_SCORE = 286,       // kimi-k3: fused res_norm*res_proj (pre-ffn)
    LLM_TENSOR_OUTPUT_RES_SCORE = 287,    // kimi-k3: fused res_norm*res_proj (final)
    LLM_TENSOR_FFN_ROUTED_DOWN = 288,     // kimi-k3: latent MoE down
    LLM_TENSOR_FFN_ROUTED_UP = 257,       // kimi-k3: latent MoE up
    LLM_TENSOR_FFN_ROUTED_NORM = 258,     // kimi-k3: latent MoE norm
    LLM_TENSOR_TIME_MIX_W0 = 96,
    LLM_TENSOR_TIME_MIX_W1 = 97,
    LLM_TENSOR_TIME_MIX_W2 = 98,
    LLM_TENSOR_TIME_MIX_A0 = 99,
    LLM_TENSOR_TIME_MIX_A1 = 100,
    LLM_TENSOR_TIME_MIX_A2 = 101,
    LLM_TENSOR_TIME_MIX_V0 = 102,
    LLM_TENSOR_TIME_MIX_V1 = 103,
    LLM_TENSOR_TIME_MIX_V2 = 104,
    LLM_TENSOR_TIME_MIX_G1 = 105,
    LLM_TENSOR_TIME_MIX_G2 = 106,
    LLM_TENSOR_TIME_MIX_K_K = 107,
    LLM_TENSOR_TIME_MIX_K_A = 108,
    LLM_TENSOR_TIME_MIX_R_K = 109,
    LLM_TENSOR_TIME_MIX_LERP_X = 110,
    LLM_TENSOR_TIME_MIX_LERP_W = 111,
    LLM_TENSOR_TIME_MIX_LERP_K = 112,
    LLM_TENSOR_TIME_MIX_LERP_V = 113,
    LLM_TENSOR_TIME_MIX_LERP_R = 114,
    LLM_TENSOR_TIME_MIX_LERP_G = 115,
    LLM_TENSOR_TIME_MIX_LERP_FUSED = 116,
    LLM_TENSOR_TIME_MIX_FIRST = 117,
    LLM_TENSOR_TIME_MIX_DECAY = 118,
    LLM_TENSOR_TIME_MIX_DECAY_W1 = 119,
    LLM_TENSOR_TIME_MIX_DECAY_W2 = 120,
    LLM_TENSOR_TIME_MIX_KEY = 121,
    LLM_TENSOR_TIME_MIX_VALUE = 122,
    LLM_TENSOR_TIME_MIX_RECEPTANCE = 123,
    LLM_TENSOR_TIME_MIX_GATE = 124,
    LLM_TENSOR_TIME_MIX_LN = 125,
    LLM_TENSOR_TIME_MIX_OUTPUT = 126,
    LLM_TENSOR_CHANNEL_MIX_LERP_K = 127,
    LLM_TENSOR_CHANNEL_MIX_LERP_R = 128,
    LLM_TENSOR_CHANNEL_MIX_KEY = 129,
    LLM_TENSOR_CHANNEL_MIX_RECEPTANCE = 130,
    LLM_TENSOR_CHANNEL_MIX_VALUE = 131,
    LLM_TENSOR_ATTN_Q_A = 132,
    LLM_TENSOR_ATTN_Q_B = 133,
    LLM_TENSOR_ATTN_KV_A_MQA = 134,
    LLM_TENSOR_ATTN_KV_B = 135,
    LLM_TENSOR_ATTN_KV = 136,
    LLM_TENSOR_ATTN_KV_NORM = 137,
    LLM_TENSOR_ATTN_OUT_A = 138,
    LLM_TENSOR_ATTN_OUT_B = 139,
    LLM_TENSOR_ATTN_K_B = 140,
    LLM_TENSOR_ATTN_V_B = 141,
    LLM_TENSOR_ATTN_Q_A_NORM = 142,
    LLM_TENSOR_ATTN_KV_A_NORM = 143,
    LLM_TENSOR_HC_HEAD_FN = 144,
    LLM_TENSOR_HC_HEAD_BASE = 145,
    LLM_TENSOR_HC_HEAD_SCALE = 146,
    LLM_TENSOR_HC_HEAD_NORM = 259,   // qwen4exp
    LLM_TENSOR_HC_HEAD_DOWN = 260,   // qwen4exp
    LLM_TENSOR_HC_HEAD_UP = 261,     // qwen4exp
    LLM_TENSOR_HC_ATTN_FN = 147,
    LLM_TENSOR_HC_ATTN_BASE = 148,
    LLM_TENSOR_HC_ATTN_SCALE = 149,
    LLM_TENSOR_HC_FFN_FN = 150,
    LLM_TENSOR_HC_FFN_BASE = 151,
    LLM_TENSOR_HC_FFN_SCALE = 152,
    LLM_TENSOR_HC_ATTN_NORM = 262,   // qwen4exp
    LLM_TENSOR_HC_ATTN_DOWN = 263,   // qwen4exp
    LLM_TENSOR_HC_ATTN_UP = 264,     // qwen4exp
    LLM_TENSOR_HC_ATTN_INJECT = 265, // qwen4exp
    LLM_TENSOR_HC_FFN_NORM = 266,    // qwen4exp
    LLM_TENSOR_HC_FFN_DOWN = 267,    // qwen4exp
    LLM_TENSOR_HC_FFN_UP = 268,      // qwen4exp
    LLM_TENSOR_HC_FFN_INJECT = 269,  // qwen4exp
    LLM_TENSOR_PLE_KEY = 270,        // qwen4exp
    LLM_TENSOR_PLE_VALUE = 271,      // qwen4exp
    LLM_TENSOR_PLE_NORM_KEY = 272,   // qwen4exp
    LLM_TENSOR_PLE_NORM_QUERY = 273, // qwen4exp
    LLM_TENSOR_PLE_NORM_CONV = 274,  // qwen4exp
    LLM_TENSOR_PLE_CONV1D = 275,     // qwen4exp
    LLM_TENSOR_ATTN_COMPRESSOR_WKV = 153,
    LLM_TENSOR_ATTN_COMPRESSOR_WGATE = 154,
    LLM_TENSOR_ATTN_COMPRESSOR_APE = 155,
    LLM_TENSOR_ATTN_COMPRESSOR_NORM = 156,
    LLM_TENSOR_ATTN_SUB_NORM = 157,
    LLM_TENSOR_FFN_SUB_NORM = 158,
    LLM_TENSOR_DEC_ATTN_NORM = 159,
    LLM_TENSOR_DEC_ATTN_Q = 160,
    LLM_TENSOR_DEC_ATTN_K = 161,
    LLM_TENSOR_DEC_ATTN_V = 162,
    LLM_TENSOR_DEC_ATTN_OUT = 163,
    LLM_TENSOR_DEC_ATTN_REL_B = 164,
    LLM_TENSOR_DEC_CROSS_ATTN_NORM = 165,
    LLM_TENSOR_DEC_CROSS_ATTN_NORM_KV = 292,
    LLM_TENSOR_DEC_CROSS_ATTN_Q = 166,
    LLM_TENSOR_DEC_CROSS_ATTN_K = 167,
    LLM_TENSOR_DEC_CROSS_ATTN_V = 168,
    LLM_TENSOR_DEC_CROSS_ATTN_OUT = 169,
    LLM_TENSOR_DEC_CROSS_ATTN_REL_B = 170,
    LLM_TENSOR_DEC_FFN_NORM = 171,
    LLM_TENSOR_DEC_FFN_GATE = 172,
    LLM_TENSOR_DEC_FFN_DOWN = 173,
    LLM_TENSOR_DEC_FFN_UP = 174,
    LLM_TENSOR_DEC_OUTPUT_NORM = 175,
    LLM_TENSOR_ENC_ATTN_NORM = 176,
    LLM_TENSOR_ENC_ATTN_Q = 177,
    LLM_TENSOR_ENC_ATTN_K = 178,
    LLM_TENSOR_ENC_ATTN_V = 179,
    LLM_TENSOR_ENC_ATTN_OUT = 180,
    LLM_TENSOR_ENC_ATTN_REL_B = 181,
    LLM_TENSOR_ENC_FFN_NORM = 182,
    LLM_TENSOR_ENC_FFN_GATE = 183,
    LLM_TENSOR_ENC_FFN_DOWN = 184,
    LLM_TENSOR_ENC_FFN_UP = 185,
    LLM_TENSOR_ENC_OUTPUT_NORM = 186,
    LLM_TENSOR_CLS = 187,
    LLM_TENSOR_CLS_OUT = 188,
    LLM_TENSOR_CLS_NORM = 189,
    LLM_TENSOR_DECISION_HIDDEN_NORM = 293,
    LLM_TENSOR_DECISION_PROJ_MEMORY = 294,
    LLM_TENSOR_DECISION_PROJ_QUESTION = 295,
    LLM_TENSOR_DECISION_PROJ_OPTION_QUESTION = 296,
    LLM_TENSOR_DECISION_PROJ_GLOBAL = 297,
    LLM_TENSOR_DECISION_PROJ_OPTION_CONTEXT = 298,
    LLM_TENSOR_DECISION_PROJ_OPTION_LEXICAL = 299,
    LLM_TENSOR_DECISION_OPTION_SUMMARY_NORM = 300,
    LLM_TENSOR_DECISION_FIELD_NORM = 301,
    LLM_TENSOR_DECISION_OPTION_NORM = 302,
    LLM_TENSOR_DECISION_SCALES = 303,
    LLM_TENSOR_DECISION_SCORER = 304,
    LLM_TENSOR_DECISION_SCORER_OUT = 305,
    LLM_TENSOR_CONV1D = 190,
    LLM_TENSOR_CONVNEXT_DW = 191,
    LLM_TENSOR_CONVNEXT_NORM = 192,
    LLM_TENSOR_CONVNEXT_PW1 = 193,
    LLM_TENSOR_CONVNEXT_PW2 = 194,
    LLM_TENSOR_CONVNEXT_GAMMA = 195,
    LLM_TENSOR_POS_NET_CONV1 = 196,
    LLM_TENSOR_POS_NET_CONV2 = 197,
    LLM_TENSOR_POS_NET_NORM = 198,
    LLM_TENSOR_POS_NET_NORM1 = 199,
    LLM_TENSOR_POS_NET_NORM2 = 200,
    LLM_TENSOR_POS_NET_ATTN_NORM = 201,
    LLM_TENSOR_POS_NET_ATTN_Q = 202,
    LLM_TENSOR_POS_NET_ATTN_K = 203,
    LLM_TENSOR_POS_NET_ATTN_V = 204,
    LLM_TENSOR_POS_NET_ATTN_OUT = 205,
    LLM_TENSOR_SHORTCONV_CONV = 206,
    LLM_TENSOR_SHORTCONV_INPROJ = 207,
    LLM_TENSOR_SHORTCONV_OUTPROJ = 208,
    LLM_TENSOR_VISEXP_ATTN_QKV = 209,
    LLM_TENSOR_VISEXP_ATTN_OUT = 210,
    LLM_TENSOR_VISEXP_FFN_GATE = 211,
    LLM_TENSOR_VISEXP_FFN_DOWN = 212,
    LLM_TENSOR_VISEXP_FFN_UP = 213,
    LLM_TENSOR_INDEXER_K_NORM = 214,
    LLM_TENSOR_INDEXER_PROJ = 215,
    LLM_TENSOR_INDEXER_ATTN_K = 216,
    LLM_TENSOR_INDEXER_ATTN_Q_B = 217,
    LLM_TENSOR_INDEXER_Q_PROJ = 218,
    LLM_TENSOR_INDEXER_K_PROJ = 219,
    LLM_TENSOR_INDEXER_Q_NORM = 220,
    LLM_TENSOR_INDEXER_COMPRESSOR_WKV = 221,
    LLM_TENSOR_INDEXER_COMPRESSOR_WGATE = 222,
    LLM_TENSOR_INDEXER_COMPRESSOR_APE = 223,
    LLM_TENSOR_INDEXER_COMPRESSOR_NORM = 224,
    LLM_TENSOR_INDEXER_KPOOL_GATE = 290,   // glm5-next: k-pool gate scores
    LLM_TENSOR_INDEXER_KPOOL_APE = 291,    // glm5-next: k-pool position bias
    LLM_TENSOR_FFN_GATE_TID2EID = 225,
    LLM_TENSOR_NEXTN_PROJ_PRE = 226,
    LLM_TENSOR_NEXTN_PROJ_POST = 227,
    LLM_TENSOR_NEXTN_EH_PROJ = 228,
    LLM_TENSOR_NEXTN_EH_PROJ_EMBD = 229,   // EXL3 MTP head: fc split per input with separate output scales
    LLM_TENSOR_NEXTN_EH_PROJ_HIDDEN = 230,
    LLM_TENSOR_NEXTN_EMBED_TOKENS = 231,
    LLM_TENSOR_NEXTN_ENORM = 232,
    LLM_TENSOR_NEXTN_HNORM = 233,
    LLM_TENSOR_NEXTN_SHARED_HEAD_HEAD = 234,
    LLM_TENSOR_NEXTN_SHARED_HEAD_NORM = 235,
    LLM_TENSOR_NEXTN_HC_HEAD_NORM = 236,
    LLM_TENSOR_NEXTN_HC_HEAD_DOWN = 237,
    LLM_TENSOR_NEXTN_HC_HEAD_UP = 238,
    LLM_TENSOR_DFLASH_FC = 239,
    LLM_TENSOR_DFLASH_HIDDEN_NORM = 240,
    LLM_TENSOR_GEMMA4_DFLASH_FC = 241,          // dot-form name (gemma4-dflash-draft GGUF)
    LLM_TENSOR_GEMMA4_DFLASH_HIDDEN_NORM = 242, // dot-form name (gemma4-dflash-draft GGUF)

    LLM_TENSOR_MASKED_EMBD_CENTROIDS = 243,
    LLM_TENSOR_MASKED_EMBD_ORDERING = 244,
    LLM_TENSOR_FC = 245,
    LLM_TENSOR_D2T = 246,
    LLM_TENSOR_DSPARK_MARKOV_W1 = 247,
    LLM_TENSOR_DSPARK_MARKOV_W2 = 248,
    LLM_TENSOR_DSPARK_CONF_PROJ = 249,
    LLM_TENSOR_DFLASH2_SELECTOR_HIDDEN = 250,
    LLM_TENSOR_DFLASH2_SELECTOR_PRED = 251,
    LLM_TENSOR_DFLASH2_SELECTOR_SUCC = 252,
    LLM_TENSOR_DFLASH2_ATTN_CONV_BASE = 253,
    LLM_TENSOR_DFLASH2_ATTN_CONV_PROJ = 254,
    LLM_TENSOR_DFLASH2_FFN_CONV_BASE = 255,
    LLM_TENSOR_DFLASH2_FFN_CONV_PROJ = 256,
    LLM_TENSOR_DFLASH_ATTN_CONV_BASE = 276,
    LLM_TENSOR_DFLASH_ATTN_CONV_PROJ = 277,
    LLM_TENSOR_DFLASH_FFN_CONV_BASE = 278,
    LLM_TENSOR_DFLASH_FFN_CONV_PROJ = 279,
    LLM_TENSOR_DFLASH_SELECTOR_PREV = 280,
    LLM_TENSOR_DFLASH_SELECTOR_NEXT = 281,
    LLM_TENSOR_DFLASH_SELECTOR_HIDDEN = 282,
    LLM_TENSOR_FFN_EXP_PROBS_B_VL = 283,
    LLM_TENSOR_HRM_Z_L_INIT = 289,
};

static_assert(LLM_TENSOR_DFLASH2_FFN_CONV_PROJ < LLM_TENSOR_DFLASH_ATTN_CONV_BASE,
              "automatic tensor IDs overlap the fork's explicitly assigned range");
static_assert(LLM_TENSOR_HRM_Z_L_INIT > LLM_TENSOR_FFN_ROUTED_DOWN,
              "new tensor IDs must also follow explicit IDs declared earlier");


enum llm_tensor_layer {
    LLM_TENSOR_LAYER_INPUT,
    LLM_TENSOR_LAYER_REPEATING,
    LLM_TENSOR_LAYER_OUTPUT,
};

struct LLM_KV {
    LLM_KV(llm_arch arch, const char * suffix = nullptr);

    llm_arch arch;
    const char * suffix;

    std::string operator()(llm_kv kv) const;
};

// helper to handle gguf constants
// usage:
//
//   const auto tn = LLM_TN(LLM_ARCH_LLAMA);
//
//   std::string name = tn(LLM_TENSOR_OUTPUT);                     -> "output"
//   std::string name = tn(LLM_TENSOR_TOKEN_EMBD, "bias");         -> "token_embd.bias"
//   std::string name = tn(LLM_TENSOR_ATTN_NORM, "weight", 3);     -> "blk.3.attn_norm.weight"
//
struct LLM_TN_IMPL {
    const llm_arch arch;
    const llm_tensor tensor;
    const char * const suffix;
    const int bid;
    const int xid;

    LLM_TN_IMPL(llm_arch arch, llm_tensor tensor, const char * suffix, int bid, int xid);

    std::string str() const;

    operator std::string() const {
        return str();
    }

    friend bool operator==(const std::string & str, const LLM_TN_IMPL & tn) {
        return str == tn.str();
    }

    friend bool operator!=(const std::string & str, const LLM_TN_IMPL & tn) {
        return str != tn.str();
    }
};

struct LLM_TN {
    LLM_TN(llm_arch arch) : arch(arch) {}

    llm_arch arch;

    LLM_TN_IMPL operator()(llm_tensor tensor, const char * suffix, int bid = -1, int xid = -1) const {
        return LLM_TN_IMPL(arch, tensor, suffix, bid, xid);
    }

    LLM_TN_IMPL operator()(llm_tensor tensor, int bid = -1, int xid = -1) const {
        return LLM_TN_IMPL(arch, tensor, nullptr, bid, xid);
    }
};


struct llm_tensor_info {
    llm_tensor_layer layer;
    ggml_op op;
};

std::vector<llm_arch> llm_arch_all();

const char * llm_arch_name(llm_arch arch);

llm_arch llm_arch_from_string(const std::string & name);

const llm_tensor_info & llm_tensor_info_for(llm_tensor tensor);

bool llm_arch_is_recurrent      (const llm_arch & arch);
bool llm_arch_is_hybrid         (const llm_arch & arch);
bool llm_arch_is_diffusion      (const llm_arch & arch);
bool llm_arch_supports_sm_tensor(const llm_arch & arch);
bool llm_arch_supports_rs_rollback(const llm_arch & arch);
bool llm_arch_supports_mixed_batch(const llm_arch & arch);
